import type { Metadata } from 'next'
import { Inter } from 'next/font/google'

import AuthSessionProvider from '@/providers/AuthSessionProvider'
import NextUIProvider from '@/providers/NextUIProvider'
import Header from '@/components/Header'
import { IParentProps } from '@/types'
import '@/styles/globals.css'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

const RootLayout = async ({ children }: IParentProps) => {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="container mx-auto px-4 max-w-6xl">
          <NextUIProvider>
            <AuthSessionProvider>
              <header>
                <Header />
              </header>
              <main>{children}</main>
            </AuthSessionProvider>
          </NextUIProvider>
        </div>
      </body>
    </html>
  )
}

export default RootLayout
